export const allProducts = [
    {
        id: 1, title: 'Classic Sugar', cat: 'donuts', price: 2.50, rating: 4.8, 
        img: '/img/catalog/donut-1.png', newest: true, popular: true,
        description: "The timeless classic. A fluffy, perfectly fried donut coated in fine sugar. Simple, sweet, and utterly satisfying.",
        images: ['/img/catalog/donut-1.png', '/img/details/detail-1-2.png', '/img/details/detail-1-3.png'],
        ingredients: ["Flour", "Sugar", "Yeast", "Egg", "Milk", "Nutmeg"],
        allergens: ["Wheat", "Egg", "Dairy"],
        reviewCount: 32,
    },
    {
        id: 2, title: 'Chocolate Glaze', cat: 'donuts', price: 3.00, rating: 4.9, 
        img: '/img/catalog/donut-2.png',
        description: "A rich and decadent dark chocolate glaze covers our signature fluffy donut. A must-have for all chocolate lovers.",
        images: ['/img/catalog/donut-2.png'],
        ingredients: ["Flour", "Sugar", "Cocoa Powder", "Yeast", "Egg", "Milk"],
        allergens: ["Wheat", "Egg", "Dairy"],
        reviewCount: 45,
    },
    {
        id: 3, title: 'Banana Cream', cat: 'donuts', price: 3.50, rating: 4.7,
        img: '/img/catalog/donut-3.png', popular: true,
        description: "A delightful donut filled with a smooth, luscious banana cream and topped with a light dusting of powdered sugar.",
        ingredients: ["Flour", "Sugar", "Banana", "Cream", "Yeast", "Egg", "Milk"],
        allergens: ["Wheat", "Egg", "Dairy"],
        reviewCount: 28,
    },
    {
        id: 4, title: 'Hibiscus Ring', cat: 'donuts', price: 3.25, rating: 4.6, 
        img: '/img/catalog/donut-4.png', newest: true,
        description: "A unique floral and tangy glaze made from real hibiscus flowers. A refreshing and exotic taste experience.",
        ingredients: ["Flour", "Sugar", "Hibiscus Extract", "Yeast", "Egg", "Milk"],
        allergens: ["Wheat", "Egg", "Dairy"],
        reviewCount: 19,
    },
    {
        id: 5, title: 'Spiced Delight', cat: 'donuts', price: 3.00, rating: 4.5, 
        img: '/img/catalog/donut-5.png',
        description: "Infused with a secret blend of African spices, this donut offers a warm and aromatic flavor that's truly one-of-a-kind.",
        ingredients: ["Flour", "Sugar", "Cinnamon", "Nutmeg", "Ginger", "Yeast", "Egg", "Milk"],
        allergens: ["Wheat", "Egg", "Dairy"],
        reviewCount: 25,
    },
    {
        id: 6, title: 'Caramel Filled', cat: 'donuts', price: 3.75, rating: 4.9, 
        img: '/img/catalog/donut-6.png', popular: true,
        description: "Bite into a soft donut to discover a gooey, rich caramel center. A sweet and satisfying treat.",
        ingredients: ["Flour", "Sugar", "Caramel", "Yeast", "Egg", "Milk"],
        allergens: ["Wheat", "Egg", "Dairy"],
        reviewCount: 38,
    },
    {
        id: 7, title: 'Ginger Juice', cat: 'drinks', price: 4.50, rating: 4.9, 
        img: '/img/catalog/drink-1.png', popular: true, newest: true,
        description: "Our famous homemade ginger juice. Spicy, sweet, and incredibly refreshing. Made from a traditional family recipe.",
        size: "350ml",
        ingredients: ["Fresh Ginger", "Pineapple", "Lemon", "Water", "Cane Sugar"],
        allergens: [],
        reviewCount: 52,
    },
    {
        id: 8, title: 'Bissap (Hibiscus)', cat: 'drinks', price: 4.00, rating: 4.8, 
        img: '/img/catalog/drink-2.png',
        description: "A popular West African drink made from hibiscus flowers, infused with mint and a hint of vanilla. A tangy delight.",
        size: "350ml",
        ingredients: ["Hibiscus Flowers", "Mint", "Vanilla", "Water", "Cane Sugar"],
        allergens: [],
        reviewCount: 41,
    },
    {
        id: 9, title: 'Mango Smoothie', cat: 'drinks', price: 5.00, rating: 4.7, 
        img: '/img/catalog/drink-3.png',
        description: "A thick and creamy smoothie blended with sweet, ripe mangoes and a touch of yogurt for a tropical escape.",
        size: "400ml",
        ingredients: ["Mango", "Yogurt", "Honey"],
        allergens: ["Dairy"],
        reviewCount: 33,
    },
    {
        id: 10, title: 'Fresh Mint Tea', cat: 'drinks', price: 3.00, rating: 4.6, 
        img: '/img/catalog/drink-4.png',
        description: "Hot, soothing, and aromatic. Our fresh mint tea is the perfect companion to any of our sweet treats.",
        size: "300ml",
        ingredients: ["Fresh Mint Leaves", "Green Tea", "Water"],
        allergens: [],
        reviewCount: 18,
    },
    {
        id: 11, title: 'Mini Donut Box', cat: 'donuts', price: 10.00, rating: 4.8, 
        img: '/img/catalog/donut-7.png', popular: true,
        description: "Can't decide? Get a box of six assorted mini-donuts to share... or not! Perfect for tasting a bit of everything.",
        ingredients: ["Varies by assortment"],
        allergens: ["Wheat", "Egg", "Dairy", "Nuts (possible trace)"],
        reviewCount: 48,
    },
    {
        id: 12, title: 'Coconut Dream', cat: 'donuts', price: 3.50, rating: 4.7, 
        img: '/img/catalog/donut-8.png',
        description: "A taste of the tropics. This donut is topped with a sweet glaze and generous flakes of toasted coconut.",
        ingredients: ["Flour", "Sugar", "Coconut Flakes", "Yeast", "Egg", "Milk"],
        allergens: ["Wheat", "Egg", "Dairy", "Coconut"],
        reviewCount: 22,
    },
    {
        id: 13, title: 'Iced Coffee', cat: 'drinks', price: 4.75, rating: 4.8, 
        img: '/img/catalog/drink-5.png', newest: true,
        description: "Bold and refreshing. Our cold-brewed iced coffee is smooth, strong, and the perfect pick-me-up.",
        size: "400ml",
        ingredients: ["Coffee Beans", "Water", "Optional Milk/Sugar"],
        allergens: ["Dairy (optional)"],
        reviewCount: 30,
    },
    {
        id: 14, title: 'Assortment Box', cat: 'donuts', price: 15.00, rating: 4.9, 
        img: '/img/catalog/donut-9.png',
        description: "The ultimate treat for any occasion. A box of six of our most popular full-sized donuts, beautifully packaged.",
        ingredients: ["Varies by assortment"],
        allergens: ["Wheat", "Egg", "Dairy", "Nuts (possible trace)"],
        reviewCount: 55,
    },
    {
        id: 15, title: 'Passion Fruit Juice', cat: 'drinks', price: 4.50, rating: 4.9, 
        img: '/img/catalog/drink-6.png',
        description: "Tangy, sweet, and bursting with tropical flavor. Made from fresh passion fruit for an authentic taste.",
        size: "350ml",
        ingredients: ["Passion Fruit", "Water", "Cane Sugar"],
        allergens: [],
        reviewCount: 39,
    },
];